# Generated by Django 2.2.4 on 2019-09-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='webcase',
            table=None,
        ),
    ]
